version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Install Dependencies and Compile"
          command: |
            echo "Installing dependencies and compiling with Maven"
            mvn compile 

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
