version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1

# Define the jobs we want to run for this project.
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Install Dependencies and Compile"
          command: |
            echo "Installing dependencies and compiling with Maven"
            mvn compile 
            mvn clean
      - run:
          name: "Checkstyle Analysis"
          command: |
            echo "Running Checkstyle"
            mvn checkstyle:check
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-report
      - run:
          name: "Generate and Publish Javadoc"
          command: |
            # Générer la Javadoc
            mvn javadoc:javadoc

            # Configurer Git
            git config user.name "Mustapha-Kdb"
            git config user.email "mustapha.genouiz@etudiant-fst.utm.tn"

            # Cloner la branche gh-pages
            git clone -b gh-pages $(git config --get remote.origin.url) gh-pages

            # Copier la Javadoc dans la branche gh-pages
            cp -r target/site/apidocs/* gh-pages/

            # Pousser les changements
            cd gh-pages
            git add .
            git commit -m "Automatically update Javadoc"
            git push origin gh-pages


  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Run Tests and Generate Coverage Report"
          command: |
            echo "Running tests with Maven"
            mvn verify 

  upload-coverage:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Upload Coverage Report to Codecov"
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml
          token: CODECOV_TOKEN


# Orchestrate our job run sequence.
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - upload-coverage:
          requires:
            - test
